version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  auth_backend:
    build: ./nginx-auth/
    ports:
      - "80:80"
